CREATE TABLE "logistics_order" (
	"order_id" varchar PRIMARY KEY NOT NULL,
	"transaction_id" varchar NOT NULL,
	"bpp_id" varchar,
	"bpp_uri" varchar,
	"provider_id" varchar,
	"state" varchar,
	"order_created_at" timestamp with time zone,
	"order_updated_at" timestamp with time zone,
	"item_id" varchar,
	"item_category_id" varchar,
	"item_descriptor_name" varchar,
	"item_quantity_count" integer,
	"fulfillment_id" varchar,
	"fulfillment_type" varchar,
	"awb_no" varchar,
	"start_instruction_code" varchar,
	"start_instruction_short_desc" varchar,
	"start_instruction_long_desc" varchar,
	"start_instruction_images" varchar[],
	"end_instruction_code" varchar,
	"end_instruction_short_desc" varchar,
	"end_instruction_long_desc" varchar,
	"end_instruction_images" varchar[],
	"start_authorization_type" varchar,
	"start_authorization_token" varchar,
	"start_authorization_valid_from" timestamp with time zone,
	"start_authorization_valid_to" timestamp with time zone,
	"end_authorization_type" varchar,
	"end_authorization_token" varchar,
	"end_authorization_valid_from" timestamp with time zone,
	"end_authorization_valid_to" timestamp with time zone,
	"quote_price_amount" numeric(18, 2),
	"quote_price_currency" varchar,
	"billing_name" varchar,
	"billing_email" varchar,
	"billing_phone" varchar,
	"payment_type" varchar,
	"payment_collected_by" varchar,
	"payment_collection_amount" numeric(18, 2),
	"linked_order_retail_order_id" varchar,
	"linked_order_product_name" varchar,
	"linked_order_quantity_count" integer,
	"linked_order_weight_unit" varchar,
	"linked_order_weight_value" numeric(18, 6),
	"linked_order_length_unit" varchar,
	"linked_order_length_value" numeric(18, 6),
	"linked_order_breadth_unit" varchar,
	"linked_order_breadth_value" numeric(18, 6),
	"linked_order_height_unit" varchar,
	"linked_order_height_value" numeric(18, 6),
	"linked_order_provider_name" varchar,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "tags" DROP CONSTRAINT "tags_exactly_one_owner";--> statement-breakpoint
ALTER TABLE "tags" ADD COLUMN "logistics_order_id" varchar;--> statement-breakpoint
CREATE INDEX "logistics_order_transaction_id_idx" ON "logistics_order" USING btree ("transaction_id");--> statement-breakpoint
ALTER TABLE "tags" ADD CONSTRAINT "tags_logistics_order_id_logistics_order_order_id_fk" FOREIGN KEY ("logistics_order_id") REFERENCES "public"."logistics_order"("order_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "tags_logistics_order_id_idx" ON "tags" USING btree ("logistics_order_id");--> statement-breakpoint
ALTER TABLE "tags" ADD CONSTRAINT "tags_exactly_one_owner" CHECK (num_nonnulls("tags"."init_order_id", "tags"."init_order_fulfillment_id", "tags"."search_provider_fulfillment_id", "tags"."logistics_order_id") = 1);