import type { OndcOnSearchResponse, OndcSearchRequest } from "../types/search/ondc.js";
import type { InitRequest } from "../types/init/internal.js";
import type { InitPayment, InitBilling } from "../types/init/internal.js";
import { SearchValidationError } from "./search-validation.js";
export class InitValidationError extends Error { constructor(message: string) { super(message); this.name = "InitValidationError"; } }
const record = (x: unknown, field: string): Record<string, any> => { if (!x || typeof x !== "object" || Array.isArray(x)) throw new InitValidationError(`${field} must be an object`); return x as Record<string, any>; };
const str = (x: unknown, field: string) => { if (typeof x !== "string" || !x.trim()) throw new InitValidationError(`${field} must be a non-empty string`); return x; };
export const parseInitRequest = (value: unknown): InitRequest => { const x = record(value, "request body"); const b = record(x.billing, "billing"); const a = record(b.address, "billing.address"); const p = record(x.payment, "payment"); const quantity = x.quantity === undefined ? 1 : x.quantity; if (typeof quantity !== "number" || !Number.isInteger(quantity) || quantity < 1) throw new InitValidationError("quantity must be a positive integer"); return { searchId: str(x.searchId,"searchId"), bppId: str(x.bppId,"bppId"), providerId: str(x.providerId,"providerId"), itemId: str(x.itemId,"itemId"), fulfillmentId: str(x.fulfillmentId,"fulfillmentId"), quantity, billing: { name: str(b.name,"billing.name"), email: b.email === undefined ? undefined : str(b.email,"billing.email"), phone: b.phone === undefined ? undefined : str(b.phone,"billing.phone"), address: { name: a.name, building: a.building, locality: a.locality, street: a.street, city: a.city, state: a.state, country: a.country, areaCode: str(a.areaCode,"billing.address.areaCode") } }, payment: { type: str(p.type,"payment.type"), collectedBy: p.collectedBy === undefined ? undefined : str(p.collectedBy,"payment.collectedBy"), amount: p.amount, currency: p.currency === undefined ? undefined : str(p.currency,"payment.currency"), settlementDetails: p.settlementDetails } as InitPayment }; };
export const parseOnInitResponse = (value: unknown): any => { const x = record(value,"callback body"); const c = record(x.context,"callback context"); if (c.action !== "on_init") throw new InitValidationError("callback context.action must be on_init"); str(c.transaction_id,"callback context.transaction_id"); if (!x.message || typeof x.message !== "object") throw new InitValidationError("callback message is required"); return value as any; };
